# Form implementation generated from reading ui file 'MainWindowUI.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AudioPlayerMainWindow(object):
    def setupUi(self, AudioPlayerMainWindow):
        AudioPlayerMainWindow.setObjectName("AudioPlayerMainWindow")
        AudioPlayerMainWindow.resize(692, 810)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AudioPlayerMainWindow.sizePolicy().hasHeightForWidth())
        AudioPlayerMainWindow.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        AudioPlayerMainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(parent=AudioPlayerMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tracks_listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.tracks_listWidget.setEnabled(True)
        self.tracks_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.tracks_listWidget.setTextElideMode(QtCore.Qt.TextElideMode.ElideLeft)
        self.tracks_listWidget.setObjectName("tracks_listWidget")
        self.verticalLayout.addWidget(self.tracks_listWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, 10, 10, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.current_image_lable = QtWidgets.QLabel(parent=self.centralwidget)
        self.current_image_lable.setEnabled(True)
        self.current_image_lable.setMinimumSize(QtCore.QSize(0, 60))
        self.current_image_lable.setText("")
        self.current_image_lable.setObjectName("current_image_lable")
        self.horizontalLayout_4.addWidget(self.current_image_lable)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.current_title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.current_title_label.setText("")
        self.current_title_label.setObjectName("current_title_label")
        self.verticalLayout_3.addWidget(self.current_title_label)
        self.current_author_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.current_author_label.setText("")
        self.current_author_label.setObjectName("current_author_label")
        self.verticalLayout_3.addWidget(self.current_author_label)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.current_duration_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.current_duration_label.setText("")
        self.current_duration_label.setObjectName("current_duration_label")
        self.horizontalLayout_4.addWidget(self.current_duration_label)
        self.play_stop_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.play_stop_button.setText("")
        self.play_stop_button.setObjectName("play_stop_button")
        self.horizontalLayout_4.addWidget(self.play_stop_button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.track_time_slider = QtWidgets.QSlider(parent=self.centralwidget)
        self.track_time_slider.setMinimumSize(QtCore.QSize(0, 20))
        self.track_time_slider.setStyleSheet("            QSlider{\n"
"            }\n"
"            QSlider::groove:horizontal {  \n"
"                height: 10px;\n"
"                margin: 0px;\n"
"                border-radius: 5px;\n"
"                background: #B0AEB1;\n"
"            }\n"
"            QSlider::handle:horizontal {\n"
"                background: #fff;\n"
"                border: 1px solid #E3DEE2;\n"
"                width: 17px;\n"
"                margin: -5px 0; \n"
"                border-radius: 8px;\n"
"            }\n"
"            QSlider::sub-page:qlineargradient {\n"
"                background: #3B99FC;\n"
"                border-radius: 5px;\n"
"            }")
        self.track_time_slider.setPageStep(0)
        self.track_time_slider.setTracking(True)
        self.track_time_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.track_time_slider.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.track_time_slider.setObjectName("track_time_slider")
        self.verticalLayout.addWidget(self.track_time_slider)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        AudioPlayerMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=AudioPlayerMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 692, 18))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        AudioPlayerMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=AudioPlayerMainWindow)
        self.statusbar.setObjectName("statusbar")
        AudioPlayerMainWindow.setStatusBar(self.statusbar)
        self.add_track_action = QtGui.QAction(parent=AudioPlayerMainWindow)
        self.add_track_action.setObjectName("add_track_action")
        self.menu.addAction(self.add_track_action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(AudioPlayerMainWindow)
        QtCore.QMetaObject.connectSlotsByName(AudioPlayerMainWindow)
        AudioPlayerMainWindow.setTabOrder(self.tracks_listWidget, self.play_stop_button)

    def retranslateUi(self, AudioPlayerMainWindow):
        _translate = QtCore.QCoreApplication.translate
        AudioPlayerMainWindow.setWindowTitle(_translate("AudioPlayerMainWindow", "Аудио Плеер"))
        self.menu.setTitle(_translate("AudioPlayerMainWindow", "Файл"))
        self.add_track_action.setText(_translate("AudioPlayerMainWindow", "Добавить трек"))
