# Form implementation generated from reading ui file 'TrackLineUI.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TrackLine(object):
    def setupUi(self, TrackLine):
        TrackLine.setObjectName("TrackLine")
        TrackLine.setEnabled(True)
        TrackLine.resize(440, 60)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TrackLine.sizePolicy().hasHeightForWidth())
        TrackLine.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(TrackLine)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MainLine = QtWidgets.QHBoxLayout()
        self.MainLine.setObjectName("MainLine")
        self.image = QtWidgets.QLabel(parent=TrackLine)
        self.image.setLineWidth(1)
        self.image.setObjectName("image")
        self.MainLine.addWidget(self.image)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.track_name = QtWidgets.QLabel(parent=TrackLine)
        self.track_name.setObjectName("track_name")
        self.verticalLayout.addWidget(self.track_name)
        self.author = QtWidgets.QLabel(parent=TrackLine)
        self.author.setObjectName("author")
        self.verticalLayout.addWidget(self.author)
        self.MainLine.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.MainLine.addItem(spacerItem)
        self.duration = QtWidgets.QLabel(parent=TrackLine)
        self.duration.setObjectName("duration")
        self.MainLine.addWidget(self.duration)
        self.horizontalLayout.addLayout(self.MainLine)

        self.retranslateUi(TrackLine)
        QtCore.QMetaObject.connectSlotsByName(TrackLine)

    def retranslateUi(self, TrackLine):
        _translate = QtCore.QCoreApplication.translate
        TrackLine.setWindowTitle(_translate("TrackLine", "Form"))
        self.image.setText(_translate("TrackLine", "TextLabel"))
        self.track_name.setText(_translate("TrackLine", "TextLabel"))
        self.author.setText(_translate("TrackLine", "TextLabel"))
        self.duration.setText(_translate("TrackLine", "TextLabel"))
