# Form implementation generated from reading ui file 'TrackCardUI.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TrackCardWidget(object):
    def setupUi(self, TrackCardWidget):
        TrackCardWidget.setObjectName("TrackCardWidget")
        TrackCardWidget.resize(600, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TrackCardWidget.sizePolicy().hasHeightForWidth())
        TrackCardWidget.setSizePolicy(sizePolicy)
        self.track_image_label = QtWidgets.QLabel(parent=TrackCardWidget)
        self.track_image_label.setGeometry(QtCore.QRect(89, 50, 421, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.track_image_label.sizePolicy().hasHeightForWidth())
        self.track_image_label.setSizePolicy(sizePolicy)
        self.track_image_label.setObjectName("track_image_label")
        self.track_name_label = QtWidgets.QLabel(parent=TrackCardWidget)
        self.track_name_label.setGeometry(QtCore.QRect(70, 440, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.track_name_label.setFont(font)
        self.track_name_label.setObjectName("track_name_label")
        self.track_author_label = QtWidgets.QLabel(parent=TrackCardWidget)
        self.track_author_label.setGeometry(QtCore.QRect(70, 470, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.track_author_label.setFont(font)
        self.track_author_label.setObjectName("track_author_label")
        self.track_slider = QtWidgets.QSlider(parent=TrackCardWidget)
        self.track_slider.setGeometry(QtCore.QRect(60, 500, 471, 31))
        self.track_slider.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.track_slider.setStyleSheet("            QSlider{\n"
"            }\n"
"            QSlider::groove:horizontal {  \n"
"                height: 10px;\n"
"                margin: 0px;\n"
"                border-radius: 5px;\n"
"                background: #B0AEB1;\n"
"            }\n"
"            QSlider::handle:horizontal {\n"
"                background: #fff;\n"
"                border: 1px solid #E3DEE2;\n"
"                width: 17px;\n"
"                margin: -5px 0; \n"
"                border-radius: 8px;\n"
"            }\n"
"            QSlider::sub-page:qlineargradient {\n"
"                background: #3B99FC;\n"
"                border-radius: 5px;\n"
"            }")
        self.track_slider.setPageStep(0)
        self.track_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.track_slider.setObjectName("track_slider")
        self.play_stop_button = QtWidgets.QPushButton(parent=TrackCardWidget)
        self.play_stop_button.setGeometry(QtCore.QRect(250, 550, 71, 61))
        self.play_stop_button.setText("")
        self.play_stop_button.setFlat(True)
        self.play_stop_button.setObjectName("play_stop_button")
        self.prev_button = QtWidgets.QPushButton(parent=TrackCardWidget)
        self.prev_button.setGeometry(QtCore.QRect(130, 560, 71, 41))
        self.prev_button.setText("")
        self.prev_button.setFlat(True)
        self.prev_button.setObjectName("prev_button")
        self.next_button = QtWidgets.QPushButton(parent=TrackCardWidget)
        self.next_button.setGeometry(QtCore.QRect(380, 560, 61, 41))
        self.next_button.setText("")
        self.next_button.setFlat(True)
        self.next_button.setObjectName("next_button")
        self.cur_track_time_label = QtWidgets.QLabel(parent=TrackCardWidget)
        self.cur_track_time_label.setGeometry(QtCore.QRect(70, 540, 35, 10))
        self.cur_track_time_label.setObjectName("cur_track_time_label")
        self.track_duration_label = QtWidgets.QLabel(parent=TrackCardWidget)
        self.track_duration_label.setGeometry(QtCore.QRect(490, 540, 35, 10))
        self.track_duration_label.setObjectName("track_duration_label")
        self.volume_slider = QtWidgets.QSlider(parent=TrackCardWidget)
        self.volume_slider.setGeometry(QtCore.QRect(370, 760, 211, 31))
        self.volume_slider.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.volume_slider.setStyleSheet("            QSlider{\n"
"            }\n"
"            QSlider::groove:horizontal {  \n"
"                height: 10px;\n"
"                margin: 0px;\n"
"                border-radius: 5px;\n"
"                background: #B0AEB1;\n"
"            }\n"
"            QSlider::handle:horizontal {\n"
"                background: #fff;\n"
"                border: 1px solid #E3DEE2;\n"
"                width: 17px;\n"
"                margin: -5px 0; \n"
"                border-radius: 8px;\n"
"            }\n"
"            QSlider::sub-page:qlineargradient {\n"
"                background: #3B99FC;\n"
"                border-radius: 5px;\n"
"            }")
        self.volume_slider.setPageStep(0)
        self.volume_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volume_slider.setObjectName("volume_slider")
        self.volume_image = QtWidgets.QPushButton(parent=TrackCardWidget)
        self.volume_image.setGeometry(QtCore.QRect(330, 760, 31, 21))
        self.volume_image.setText("")
        self.volume_image.setFlat(True)
        self.volume_image.setObjectName("volume_image")

        self.retranslateUi(TrackCardWidget)
        QtCore.QMetaObject.connectSlotsByName(TrackCardWidget)
        TrackCardWidget.setTabOrder(self.track_slider, self.play_stop_button)
        TrackCardWidget.setTabOrder(self.play_stop_button, self.prev_button)
        TrackCardWidget.setTabOrder(self.prev_button, self.next_button)

    def retranslateUi(self, TrackCardWidget):
        _translate = QtCore.QCoreApplication.translate
        TrackCardWidget.setWindowTitle(_translate("TrackCardWidget", "Form"))
        self.track_image_label.setText(_translate("TrackCardWidget", "TextLabel"))
        self.track_name_label.setText(_translate("TrackCardWidget", "TextLabel"))
        self.track_author_label.setText(_translate("TrackCardWidget", "TextLabel"))
        self.cur_track_time_label.setText(_translate("TrackCardWidget", "TextLabel"))
        self.track_duration_label.setText(_translate("TrackCardWidget", "TextLabel"))
